name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: install dependencies
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo install cargo-audit

      - name: run ci checks
        run: make ci
