name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
    runs-on: ${{ matrix.target == 'x86_64-apple-darwin' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: rename binary
        run: |
          cd target/${{ matrix.target }}/release
          mv devx devx-${{ matrix.target }}

      - name: publish binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/devx-${{ matrix.target }}

  verify:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install binary
        run: |
          curl -sSL https://raw.githubusercontent.com/ajndkr/devx/main/install.sh | bash

      - name: verify installation
        run: devx help

      - name: cleanup
        run: devx manage uninstall
