name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
    runs-on: ${{ matrix.target == 'x86_64-apple-darwin' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: rename binary
        run: |
          cd target/${{ matrix.target }}/release
          mv devx devx-${{ matrix.target }}

      - name: publish executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/devx-${{ matrix.target }}
